apiVersion: v1
kind: Pod
metadata:
  labels:
    run: iperf-client
  name: iperf-client
spec:
  containers:
  - args:
    - sleep
    - 2d
    image: infrabuilder/netbench
    name: iperf-cli
  nodeSelector: 
    kubernetes.io/hostname: s03
  restartPolicy: Never
